import { Button, ColorModeScript, Container, Flex } from "@chakra-ui/react";
import { Text, HStack } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import theme from "./theme";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { MenuItem } from "../components/molecules/MenuItem/MenuItem";
import { Hero } from "../components/molecules/Hero/Hero";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>WalidApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ColorModeScript initialColorMode={theme.config.initialColorMode} />

      <Flex w="100%" alignContent="center" flexDirection="row" p="6px 0">
        <Text
          fontSize="36px"
          fontWeight="bold"
          lineHeight="42px"
          color="#1F79BA"
          flexGrow={1}
        >
          WalidApp
        </Text>
        <HStack spacing="16px" alignContent="center">
          <MenuItem>
            <Link href="/blog">
              <a>Blog</a>
            </Link>
          </MenuItem>
          <MenuItem>
            <Link href="/product">
              <a>Product</a>
            </Link>
          </MenuItem>
          <MenuItem>
            <Link href="/pricing">
              <a>Pricing</a>
            </Link>
          </MenuItem>
        </HStack>
        <Flex marginLeft="82px">
          <Button variant="solid" color="white" colorScheme="blue">
            Get Started
          </Button>
        </Flex>
      </Flex>
      <Flex>
        <Hero />
      </Flex>
    </div>
  );
};

export default Home;
