import { Flex } from "@chakra-ui/layout";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Hero } from "../components/molecules/Hero/Hero";
import { TopBar } from "../components/organisms/TopBar/TopBar";
import { LandingBody } from "../components/molecules/LandingBody/LandingBody";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>WalidApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopBar />

      <Flex>
        <Hero />
      </Flex>
      <LandingBody />
    </div>
  );
};

export default Home;
