import { ColorModeScript } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import theme from "./theme";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Walid's App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ColorModeScript initialColorMode={theme.config.initialColorMode} />
    </div>
  );
};

export default Home;
